name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
    - name: Install packages
      run:
        sudo apt update
        sudo apt install libwebkit2gtk-4.0-dev
        sudo apt install build-essential 
        sudo apt install curl 
        sudo apt install wget 
        sudo apt install libssl-dev 
        sudo apt install libgtk-3-dev 
        sudo apt install libayatana-appindicator3-dev 
        sudo apt install librsvg2-dev
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
